#!/bin/sh

#podman run -it --systemd --device /dev/dri -e DISPLAY=$DISPLAY -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /tmp --tmpfs /run -v /tmp/.X11-unix:/tmp/.X11-unix -v /run/user/1000/bus:/tmp/bus -v "$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY":/tmp/wayland-0 wayland-container bash
#sudo podman run -it --rm --net=host -v $(realpath home):/home/student --device /dev/dri --privileged -v "$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY":/tmp/wayland-0 -e WAYLAND_DISPLAY=/tmp/wayland-0 -e DISPLAY=$DISPLAY -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v /run/user/1000/bus:/tmp/bus -v /tmp/.X11-unix:/tmp/.X11-unix --tmpfs /tmp --tmpfs /run wayland-container /sbin/init
#sudo podman run -it --net=host -v $(realpath home):/home/student --device /dev/dri -e DISPLAY=$DISPLAY -v /sys/fs/cgroup:/sys/fs/cgroup:Z --tmpfs /tmp --tmpfs /run -v /tmp/.X11-unix:/tmp/.X11-unix:Z -v /run/user/1000/bus:/tmp/bus:Z -v "$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY":/tmp/wayland-0:Z wayland-container


sudo podman build -t wayland-container .
mkdir -p home
sudo podman run -it --rm --net=host -v $(realpath home):/home/student --device /dev/dri -e DISPLAY=$DISPLAY -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /tmp --tmpfs /run -v /tmp/.X11-unix:/tmp/.X11-unix:Z -v /run/user/1000/bus:/tmp/bus:Z -v "$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY":/tmp/wayland-0:Z wayland-container