#!/bin/sh

RESOLUTION=$(zenity --list --title="Select a resolution" --column="Resolution" 640x400 800x510 1366x668 1400x610 1920x1000)
export MUTTER_DEBUG_DUMMY_MODE_SPECS=$RESOLUTION
export MUTTER_DEBUG_DUMMY_MONITOR_SCALES=1
dbus-run-session -- gnome-shell --nested --wayland